apiVersion: v2
name: kleidia-services
version: 2.4.1
description: Kleidia application layer (backend, frontend)
type: application
appVersion: "2.4.1"
keywords:
  - backend
  - frontend
  - api
maintainers:
  - name: Kleidia Team

