apiVersion: v2
name: kleidia-data
version: 2.2.5
description: Kleidia data layer (PostgreSQL) - HTTP-based agent architecture
type: application
appVersion: "2.2.5"
keywords:
  - postgresql
maintainers:
  - name: Kleidia Team

